/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Event.Event;
import Business.GoogleAPIs.GroupEmail;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.EventManagemnetOrg;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RoleWorkRequest;
import Business.Zone.Zone;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ragha
 */
public class RegisterForEvent extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EventManagemnetOrg organization;
    private EcoSystem system;
    private boolean flag = false;

    /**
     * Creates new form EventManager
     */
    public RegisterForEvent(JPanel userProcessContainer, UserAccount account, EventManagemnetOrg organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        populateEventComboBox();
    }

    private void populateEventComboBox() {
        eventNameField.removeAllItems();

        for (Event event : system.getEventDirectory().getEventList()) {
            eventNameField.addItem(event);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registerForEventBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EventDetailsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EventIDTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EventNameTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        eventVenueTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EventDateTxt = new javax.swing.JTextField();
        RegStartTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RegEndTxt = new javax.swing.JTextField();
        eventNameField = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Select an Event : ");

        registerForEventBtn.setText("Register for event");
        registerForEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerForEventBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Register For Event");

        EventDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        EventDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Event Details :");
        EventDetailsPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 140, 30));

        EventIDTxt.setEditable(false);
        EventDetailsPanel.add(EventIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 230, -1));

        jLabel4.setText("Event ID");
        EventDetailsPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 60, 114, 20));

        jLabel5.setText("Event name");
        EventDetailsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 90, 114, 20));

        EventNameTxt.setEditable(false);
        EventDetailsPanel.add(EventNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 230, -1));

        jLabel6.setText("Venue");
        EventDetailsPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 120, 114, 20));

        eventVenueTextField.setEditable(false);
        EventDetailsPanel.add(eventVenueTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 230, -1));

        jLabel7.setText("Event Date");
        EventDetailsPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 150, 114, 20));

        EventDateTxt.setEditable(false);
        EventDetailsPanel.add(EventDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 230, -1));

        RegStartTxt.setEditable(false);
        EventDetailsPanel.add(RegStartTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 230, -1));

        jLabel9.setText("Registration starts on");
        EventDetailsPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 185, -1, 20));

        jLabel10.setText("Registration ends by");
        EventDetailsPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 218, 104, 20));

        RegEndTxt.setEditable(false);
        EventDetailsPanel.add(RegEndTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 230, -1));

        eventNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNameFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addComponent(eventNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(registerForEventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(EventDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(EventDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerForEventBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerForEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerForEventBtnActionPerformed
        Event selectedEvent = (Event) eventNameField.getSelectedItem();
        RoleWorkRequest newRequest = new RoleWorkRequest();
        Random rand = new Random();
        newRequest.setWorkRequestId(rand.nextInt(50) + 1);
        newRequest.setSender(userAccount);
        newRequest.setUserAccount(userAccount);
        newRequest.setMessage(selectedEvent.getEventName());
        newRequest.setEventVenue(selectedEvent.getVenue());

        Organization org = null;
        for (Network eachNetwork : system.getNetworkDirectory().getNetworkList()) {
            for (Zone eachZone : eachNetwork.getZoneDirectory().getZoneList()) {
                for (Enterprise eachEnterprise : eachZone.getEnterpriseDirectory().getEnterpriseList()) {
                    for (Organization eachOrg : eachEnterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (eachOrg instanceof EventManagemnetOrg) {
                            org = eachOrg;
                            break;
                        }
                    }
                }
            }
        }
        if (org != null) {
            org.getWorkQueue().addNewRequest(newRequest);
            userAccount.getWorkQueue().addNewRequest(newRequest);
        }
        system.addRegisteredEventUser(userAccount);
        JOptionPane.showMessageDialog(null, "Successfully registered for the event!!");
//        GroupEmail.sendMail(selectedEvent, userAccount);
    }//GEN-LAST:event_registerForEventBtnActionPerformed

    private void eventNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNameFieldActionPerformed
        // populate the event details
        Event event = (Event) eventNameField.getSelectedItem();
        if (event != null) {
            EventIDTxt.setText(String.valueOf(event.getEventId()));
            EventNameTxt.setText(event.getEventName());
            eventVenueTextField.setText(event.getVenue());
            EventDateTxt.setText(event.getEventDate().toString());
            RegStartTxt.setText(event.getRegStartDate().toString());
            RegEndTxt.setText(event.getRegEndDate().toString());
        }

    }//GEN-LAST:event_eventNameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EventDateTxt;
    private javax.swing.JPanel EventDetailsPanel;
    private javax.swing.JTextField EventIDTxt;
    private javax.swing.JTextField EventNameTxt;
    private javax.swing.JTextField RegEndTxt;
    private javax.swing.JTextField RegStartTxt;
    private javax.swing.JComboBox<Object> eventNameField;
    private javax.swing.JTextField eventVenueTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton registerForEventBtn;
    // End of variables declaration//GEN-END:variables
}
