/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EventManagemnetOrg;
import Business.UserAccount.UserAccount;
import UserInterface.AdministrativeRole.ManageOrganizationJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Divya Priya Emmanuel
 */
public class UserOptionJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EventManagemnetOrg organization;
    private EcoSystem system;
    /**
     * Creates new form UserOptionJPanel
     */
    public UserOptionJPanel(JPanel userProcessContainer, UserAccount userAccount, EventManagemnetOrg organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        OptionRegTxt = new javax.swing.JButton();
        EditProTxt = new javax.swing.JButton();
        OptionDashboardTxt = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select your options");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 280, -1));

        OptionRegTxt.setText("Register for an event !!");
        OptionRegTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionRegTxtActionPerformed(evt);
            }
        });
        add(OptionRegTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        EditProTxt.setText("Edit my profile");
        EditProTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProTxtActionPerformed(evt);
            }
        });
        add(EditProTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 320, 140, 20));

        OptionDashboardTxt.setText("Dash Board");
        OptionDashboardTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionDashboardTxtActionPerformed(evt);
            }
        });
        add(OptionDashboardTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void OptionRegTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionRegTxtActionPerformed
        // TODO add your handling code here:
        
        RegisterForEvent registerForEvent = new RegisterForEvent(userProcessContainer, userAccount, organization, enterprise, system);
        userProcessContainer.add("registerForEvent", registerForEvent);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_OptionRegTxtActionPerformed

    private void EditProTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProTxtActionPerformed
        // TODO add your handling code here:
        UserEditProfileJPanel userEditProfileJPanel = new UserEditProfileJPanel(userProcessContainer, userAccount, organization, enterprise, system);
        userProcessContainer.add("userEditProfileJPanel", userEditProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_EditProTxtActionPerformed

    private void OptionDashboardTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionDashboardTxtActionPerformed
        // TODO add your handling code here:
        DashboardForUser dashboardForUser = new DashboardForUser(userProcessContainer, userAccount, organization, enterprise, system);
        userProcessContainer.add("dashboardForUser", dashboardForUser);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_OptionDashboardTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditProTxt;
    private javax.swing.JButton OptionDashboardTxt;
    private javax.swing.JButton OptionRegTxt;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
