/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EventManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EventManagemnetOrg;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Divya Priya Emmanuel
 */
public class EventManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEventJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EventManagemnetOrg organization;
    private EcoSystem system;
    private boolean flag = false;

    public EventManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EventManagemnetOrg organization, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        ViewAllEventsBtn = new javax.swing.JButton();
        WorkRequestBtn = new javax.swing.JButton();
        addNewEventBtn = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Event Manager Work Area Panel");

        ViewAllEventsBtn.setText("View All Events");
        ViewAllEventsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllEventsBtnActionPerformed(evt);
            }
        });

        WorkRequestBtn.setText("Work Request");
        WorkRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkRequestBtnActionPerformed(evt);
            }
        });

        addNewEventBtn.setText("Add a new Event");
        addNewEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEventBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(WorkRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addNewEventBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ViewAllEventsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(279, 279, 279))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel3)
                .addGap(63, 63, 63)
                .addComponent(ViewAllEventsBtn)
                .addGap(18, 18, 18)
                .addComponent(addNewEventBtn)
                .addGap(18, 18, 18)
                .addComponent(WorkRequestBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewAllEventsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllEventsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewAllEventsBtnActionPerformed

    private void WorkRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkRequestBtnActionPerformed
        ManageWorkRequestPanel manageWorkRequestJPanel = new ManageWorkRequestPanel(userProcessContainer, userAccount, organization, system);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageWorkRequestPanel", manageWorkRequestJPanel);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_WorkRequestBtnActionPerformed

    private void addNewEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewEventBtnActionPerformed
        CreateEventJPanel createEventJPanel = new CreateEventJPanel(userProcessContainer, system);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("createEventJPanel", createEventJPanel);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_addNewEventBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewAllEventsBtn;
    private javax.swing.JButton WorkRequestBtn;
    private javax.swing.JButton addNewEventBtn;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
