/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EventManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EventManagemnetOrg;
import Business.Organization.Organization;
import Business.Organization.TransportOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RoleWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.Zone.Zone;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Event.Event;
import java.awt.Component;
import java.util.Date;

/**
 *
 * @author Divya Priya Emmanuel
 */
public class UpdateEventJpanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EventManagemnetOrg organization;
    private EcoSystem system;
    private Event event;
    /**
     * Creates new form UpdateEventJpanel
     */
    public UpdateEventJpanel(JPanel userProcessContainer, UserAccount userAccount, EventManagemnetOrg organization, EcoSystem system, Event event) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.system = system;
        this.event = event;
        populateEvent();
    }
    
    public void populateEvent(){
        EventDateChooser.setMinSelectableDate(new Date());
        eventNameTxt.setText(event.getEventName());
        venueEventTxt.setText(event.getVenue());
        EventDateChooser.setDate(event.getEventDate());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventNameTxt = new javax.swing.JTextField();
        venueEventTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EventDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNameTxtActionPerformed(evt);
            }
        });
        add(eventNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 90, -1));
        add(venueEventTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 90, -1));

        jLabel1.setText("Event Date:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 90, -1));

        jLabel2.setText("Event Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, -1));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 170, 90, 20));
        add(EventDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 272, -1, -1));

        jLabel4.setText("Venue:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Update the selected Event ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 270, -1));

        SaveBtn.setText("Save Change");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 348, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 414, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ragha\\Desktop\\4.jpg")); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 166, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void eventNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventNameTxtActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        event.setEventDate(EventDateChooser.getDate());
        event.setEventName(eventNameTxt.getText());
        event.setVenue(venueEventTxt.getText());
        JOptionPane.showMessageDialog(null, "Event details has been updated successfully !!");
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();        
        Component component = componentArray[componentArray.length - 1];        
        ViewAllEventJPanel adminPanel = (ViewAllEventJPanel) component; 
        adminPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser EventDateChooser;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField eventNameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField venueEventTxt;
    // End of variables declaration//GEN-END:variables
}
